### PR TITLE
Addressing reviewer comments

### PR DESCRIPTION
**Pull request by kuziekj**
I'm starting to address the various comments from the devs.

I removed references to 'fnirs_fd_phase' since I think, like the devs suggest, it might be best to add this in a separate PR. In this separate PR we can also add things like 'fnirs_fd_dc' and 'fnirs_fd_ac', along with proper tests.

I still have some comments to address but there are a couple I'm not sure how to address:

-they would like us to test that the returned data types are what the user specifies (eg. specify 'DC' and test that 'DC' is actually confirmed). I'm not sure how to actually do this since we don't change the channel type based on the data type specified, so maybe such a test isn't needed at the moment. Comparing the values to p_pod kind of already tests this anyway, since it it doesn't grab the correct data type the p_pod comparison would fail.

-they also ask 

> Can we test the boxy version number is supported?

but I'm not sure how to do this...

### CODE REVIEW

**Comment by kylemath** [comment]
ok they have replied on the PR so I am not sure this PR is still correct, they did not want us to full on remove things, and I am confused what they currently do want us to do, I suggest talking with them on the PR page to get a good sense of what they want

do the boxy data files have version numbers in them anywhere? This would involve looking up those version numbers against.a list we keep of ones we know work with this tool

**Comment by kylemath** [comment]
ok I'll approve to merge this into importBOXY
I will comment in the mne forum once you do that and I can see the comparison between the master and our changes more clearly

**Review by kylemath — APPROVED** [review]

**Comment by kuziekj** [comment]
Okay so I think this does address most of the devs comments, aside from the comments related to channel types since those changes were removed. The reader should now always return all three data types, and I've changed/added tests.

I took a look at using `.pick` to select 'DC', 'AC', or 'Ph' data, and I have an idea where to start (specifically within `_picks_str_to_idx` in `mne/io/pick.py`). I imagine the best way would be to have the user pass a string ('DC', 'AC', 'Ph') and then have .pick grab the appropriate channels based on channel type.....but since we aren't adding new channels types in this PR, that will have to wait. I can ask the devs about this once we think these changes are okay and merged.

Oh, also let me know if we should be more descriptive regarding DC, AC, and Phase in the tutorial. Devs seem worried new users will get confused about what those data types are.

**Comment by kylemath** [comment]
ok I'll approve to merge this into importBOXY
I will comment in the mne forum once you do that and I can see the comparison between the master and our changes more clearly

**Review by kylemath — APPROVED** [review]
ok I'll approve to merge this into importBOXY
I will comment in the mne forum once you do that and I can see the comparison between the master and our changes more clearly

**Pull request merged**
