### PR TITLE
Plotting hbo and hbr evoked activity within events

### PR DESCRIPTION
**Pull request by kuziekj**
I changed how hbo and hbr evoked activity are plotted for events 1 and 2. Now it creates 3 subplots:

subplot 1 = 3 lines for event 1 (hbo, hbr, hbo minus hbr)
subplot 2 = 3 lines for event 2 (hbo, hbr, hbo minus hbr)
subplot 3 = 1 line (event 1 difference minus event 2 difference)

Is this kind of how you wanted these plotted (although maybe one plot instead of subplots)?
new_plot

I also kept the original way of plotting (lines 260-271) 
orig_plot

and an alternative way of plotting hbo and hbr together (lines 274-290, legend doesn't update properly for this one), just for comparison. I'll remove these once we're happy with any changes.
alt_plot

I had to make the subplots manually instead of using the built-in plotting functions (like plot_compare_evokeds) since those functions return errors if the data you are trying to plot has different channel names (in this case, some channels are hbo and others are hbr).

I also made a small change to line 16 so that it hopefully links to the boxy data
set instead of the fnirs motor dataset.

### CODE REVIEW

**Comment by kylemath** [comment]
I'll test tonight , I like the top plots alot, I think the rightmost plot
should have both event 1 and event 2 and their difference

**Comment by kuziekj** [comment]
okay, I added the event 1 and event 2 differences to the third subplot. Colours might not be the best but we can adjust that.

**Review by kylemath — CHANGES_REQUESTED** [review]
just tested it
I think remove this plot: 
Screen Shot 2020-06-26 at 12 20 09 AM
and keep the second way, but those line graphs were too big for the axis size:
Screen Shot 2020-06-26 at 12 22 17 AM

**Comment by kuziekj** [comment]
Okay, I removed the older way of making these plots and kept the new way.

I'm confused though, my plots don't look like yours:

new_plot

I deleted the 'MNE-BOXY-example-data' to make it redownload the data, just in case I made changes I forgot about, but the plots still look different. Any idea why this might be?

**Comment by kylemath** [comment]
well yes that is certainly weird,
maybe I need to download the new data, but I don't think that makes sense/

**Comment by kuziekj** [comment]
Hmmm, so I'm assuming it's something to do with my setup since you seem to be getting similiar plots to what the CI tests produce (based on the plot you said to remove in a previous comment).

Here are the links for CI tests:
https://20838-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/preprocessing/plot_80_boxy_processing.html?highlight=boxy
https://20838-1301584-gh.circle-artifacts.com/0/dev/generated/mne.io.read_raw_boxy.html?highlight=boxy#mne.io.read_raw_boxy

I tried cloning our fork again, in case I had modified files that were causing an issue, but that didn't change anything. The difference seems to occur once epochs are made, since the raw data looks comparable to the CI test. I'll attach some of the figures I get.

raw_ac
epoch_ac
hbo_ac_1
hbr_ac_1
hbo_ac_2
hbr_ac_2

Maybe it's an issue with my environment, maybe a package is a different version. I'll test that out next.

**Comment by kuziekj** [comment]
Updated this so that the table of contents now shows up properly after building the html. 

image

The html link still shows an 'out' section in some areas and I'm not sure why. I tried commenting out our print statements but the output from some of the mne functions are still showing.

image

Anyway, if you want to make the html locally, this is what I did in git bash.

- cd git_repos/mne-python/doc
- conda activate mnedev
- PATTERN=plot_80_boxy_processing.py make html_dev-pattern
- make show

Actually I just checked and I think we can ignore the output segments I mentioned above, I think they're just for us to make sure things are doing what we want. If I run "PATTERN=plot_70_fnirs_processing.py make html_dev-pattern" then the plot_70 tutorial will have the output sections too.

**Comment by kylemath** [comment]
looks great to me, well done

**Review by kylemath — APPROVED** [review]

**Pull request merged**
