### PR TITLE
Simple tutorial

### PR DESCRIPTION
**Pull request by kuziekj**
A start to simplifying the tutorial, with less plots and AC data plotted separately from phase data. Producing more than 20 plots results in matplotlib returning a runtime warning, causing the CI tests to fail. Only 18 plots are created throughout the whole tutorial, although perhaps this can be further reduced.

### CODE REVIEW

**Comment by kylemath** [comment]
looks good to me, I want to see it in the html so go ahead and merge and send me the link

**Review by kylemath — APPROVED** [review]

**Comment by kylemath** [comment]
Screen Shot 2020-06-22 at 11 37 09 PM

I don't this this difference is correct, 
I think we want to compare oxy and deoxy for each event
and then compute teh differences between them, and compare them between events

**Comment by kylemath** [comment]
looks really good jon, well done!

**Comment by kuziekj** [comment]
Okay, so plot oxy and deoxy for event 1 (first plot) and event 2 (second plot) along with the difference? Then a third plot showing the difference between oxy and deoxy for both events (something like a plot with two green lines)? I'll work on those changes, but I'll merge first so we can see how the tests go.

**Pull request merged**
